name = "NonlinearChemomechanics"
uuid = "6c551e3e-5032-4b09-afbe-8d43dfe5e6f9"
authors = ["Ivan Utkin <iutkin@ethz.ch>"]
version = "0.1.0"

[deps]
ParallelStencil = "94395366-693c-11ea-3b26-d9b7aac5d958"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
